services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    container_name: metal-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: defaultdb
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: random-band/Dockerfile
    platform: linux/arm64
    container_name: random-band
    restart: always
    ports:
      - "80:80"
    environment:
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
      - TLS_ENABLED=false
      - REVERSE=true
    depends_on:
      - db 